"""PDF generation service for analysis reports and pitch decks."""

import re
import textwrap
from fpdf import FPDF


# ---------- Colours ----------
_DARK_BG = (10, 14, 26)
_CARD_BG = (22, 30, 50)
_ACCENT = (99, 102, 241)
_WHITE = (241, 245, 249)
_MUTED = (148, 163, 184)
_SUCCESS = (52, 211, 153)


class _BasePDF(FPDF):
    """Shared dark‑themed PDF base."""

    def __init__(self, title: str, **kwargs):
        super().__init__(**kwargs)
        self._doc_title = title
        self.set_auto_page_break(auto=True, margin=20)
        self.set_margins(18, 18, 18)

    # ── header ──
    def header(self):
        self.set_fill_color(*_DARK_BG)
        self.rect(0, 0, 210, 297, "F")  # A4 dark background
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*_MUTED)
        self.cell(0, 8, self._doc_title, align="L")
        self.ln(12)

    # ── helpers ──
    def _section_title(self, text: str):
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(*_ACCENT)
        self.cell(0, 10, text, new_x="LMARGIN", new_y="NEXT")
        # accent bar
        self.set_fill_color(*_ACCENT)
        self.rect(self.l_margin, self.get_y(), 40, 1, "F")
        self.ln(4)

    def _body_text(self, text: str):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(*_WHITE)
        for line in text.split("\n"):
            stripped = line.strip()
            if not stripped:
                self.ln(3)
                continue
            # bullet points
            if stripped.startswith(("- ", "* ", "• ")):
                self.set_x(self.l_margin + 4)
                self.set_font("Helvetica", "", 10)
                self.set_text_color(*_WHITE)
                self.multi_cell(0, 5.5, "  •  " + stripped.lstrip("-*• ").strip())
            # sub‑headings (markdown ## or bold **)
            elif stripped.startswith("#"):
                clean = stripped.lstrip("# ").strip()
                self._section_title(clean)
            elif stripped.startswith("**") and stripped.endswith("**"):
                clean = stripped.strip("*").strip()
                self._section_title(clean)
            else:
                self.multi_cell(0, 5.5, stripped)
        self.ln(3)

    def _card_block(self, title: str, content: str):
        """Renders a titled card with dark background."""
        x = self.l_margin
        y = self.get_y()

        # estimate height
        lines = content.count("\n") + 3
        estimated_h = max(lines * 5.5 + 20, 30)
        if y + estimated_h > 277:
            self.add_page()
            y = self.get_y()

        # card bg
        self.set_fill_color(*_CARD_BG)
        w = 210 - self.l_margin - self.r_margin
        self.rect(x, y, w, estimated_h, "F")

        self.set_xy(x + 4, y + 4)
        self._section_title(title)
        self.set_x(x + 4)
        self._body_text(content)
        self.ln(6)


def _clean_markdown(text: str) -> str:
    """Light cleanup of markdown for PDF rendering."""
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)  # remove bold markers
    text = re.sub(r"__(.+?)__", r"\1", text)
    text = re.sub(r"\*(.+?)\*", r"\1", text)
    text = re.sub(r"_(.+?)_", r"\1", text)
    text = re.sub(r"`(.+?)`", r"\1", text)
    return text.strip()


# ═══════════════════════════════════════════
#  Public API
# ═══════════════════════════════════════════

def generate_analysis_pdf(
    startup_name: str,
    analysis_text: str,
    market_text: str,
    action_plan: list[str],
) -> bytes:
    """Generate a styled analysis report PDF. Returns raw bytes."""
    pdf = _BasePDF(title=f"{startup_name} — Analysis Report")
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(*_ACCENT)
    pdf.cell(0, 12, startup_name, new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(*_MUTED)
    pdf.cell(0, 8, "Startup Analysis Report", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(10)

    # Analysis
    pdf._section_title("Detailed Startup Analysis")
    pdf._body_text(_clean_markdown(analysis_text))

    # Market Research
    pdf.add_page()
    pdf._section_title("Market Research Insights")
    pdf._body_text(_clean_markdown(market_text))

    # Action Plan
    if action_plan:
        pdf.add_page()
        pdf._section_title("Recommended Action Plan")
        for i, item in enumerate(action_plan, 1):
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(*_WHITE)
            pdf.multi_cell(0, 6, f"  {i}.  {item}")
            pdf.ln(2)

    # Footer
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(*_MUTED)
    pdf.cell(0, 10, "Generated by AI Startup Builder", align="C")

    return pdf.output()


def generate_pitch_deck_pdf(
    startup_name: str,
    pitch_deck_text: str,
) -> bytes:
    """Generate a styled pitch deck PDF. Returns raw bytes."""
    pdf = _BasePDF(title=f"{startup_name} — Pitch Deck")

    # Parse slides from the pitch deck text
    slides = _parse_slides(pitch_deck_text)

    for i, slide in enumerate(slides):
        pdf.add_page()

        if i == 0:
            # Title slide — centered, large
            pdf.ln(60)
            pdf.set_font("Helvetica", "B", 28)
            pdf.set_text_color(*_ACCENT)
            pdf.cell(0, 14, startup_name, new_x="LMARGIN", new_y="NEXT", align="C")
            pdf.ln(4)
            pdf.set_font("Helvetica", "", 13)
            pdf.set_text_color(*_WHITE)
            tagline = slide.get("content", "").strip()
            if tagline:
                pdf.multi_cell(0, 7, tagline, align="C")
            pdf.ln(20)
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(*_MUTED)
            pdf.cell(0, 8, "AI-Generated Pitch Deck", new_x="LMARGIN", new_y="NEXT", align="C")
        else:
            # Content slide
            pdf._section_title(slide.get("title", f"Slide {i + 1}"))
            pdf._body_text(_clean_markdown(slide.get("content", "")))

        # slide number
        pdf.set_y(280)
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*_MUTED)
        pdf.cell(0, 5, f"{i + 1} / {len(slides)}", align="R")

    return pdf.output()


def _parse_slides(text: str) -> list[dict]:
    """Parse pitch deck text into slides. Expects ## headings as slide separators."""
    slides = []
    current_title = ""
    current_lines = []

    for line in text.split("\n"):
        stripped = line.strip()
        if stripped.startswith("## ") or stripped.startswith("# "):
            if current_title or current_lines:
                slides.append({
                    "title": current_title,
                    "content": "\n".join(current_lines).strip(),
                })
            current_title = stripped.lstrip("# ").strip()
            current_lines = []
        else:
            current_lines.append(line)

    if current_title or current_lines:
        slides.append({
            "title": current_title,
            "content": "\n".join(current_lines).strip(),
        })

    # If no slides parsed, treat entire text as one slide
    if not slides:
        slides = [{"title": "Overview", "content": text.strip()}]

    return slides
