# workflows/startup_workflow.py

import re
import time
from typing import Dict

from crewai import Crew
from litellm.exceptions import RateLimitError

from agents.idea_analyzer import idea_analyzer_agent
from agents.market_researcher import market_research_agent
from agents.tasks import idea_analysis_task, market_research_task, website_generation_task
from agents.website_generator import website_generator_agent
from services.github_service import create_github_repo
from services.vercel_service import deploy_to_vercel

REQUIRED_SITE_FILES = [
    "index.html",
    "about.html",
    "pricing.html",
    "contact.html",
    "styles.css",
    "script.js",
    "README.md",
]


def safe_step(agent, task, inputs, retries=2, wait_time=5):
    for _ in range(retries):
        try:
            step_crew = Crew(
                agents=[agent],
                tasks=[task],
                verbose=False,
            )
            return step_crew.kickoff(inputs=inputs)
        except RateLimitError:
            print(f"[WARN] Rate limit hit. Retrying in {wait_time} seconds...")
            time.sleep(wait_time)
    raise Exception("[ERROR] Max retries exceeded due to rate limits.")


def preprocess_idea(startup_idea: str) -> dict:
    name_match = re.search(r"(called|named)\s+([A-Za-z0-9\s]+)", startup_idea, re.I)
    startup_name = name_match.group(2).strip() if name_match else "my-startup"
    return {
        "startup_name": startup_name,
        "description": startup_idea,
        "target_users": None,
        "features": None,
        "tone": None,
        "cta": None,
    }


def _recommended_action_plan(structured_idea: dict) -> list[str]:
    startup_name = structured_idea.get("startup_name", "startup").strip() or "startup"
    return [
        f"Define MVP scope and success metrics for {startup_name}.",
        "Interview target users and validate pain points with evidence.",
        "Launch and test the generated website with clear CTA tracking.",
        "Run small acquisition experiments and compare conversion performance.",
        "Iterate product roadmap based on usage, retention, and feedback data.",
    ]


def _extract_raw_text(result) -> str:
    try:
        return result.raw
    except AttributeError:
        return str(result)


def _sanitize_file_path(path: str) -> str:
    clean = path.strip().replace("\\", "/")
    clean = clean.lstrip("./")
    if not clean or clean.startswith("/") or ".." in clean.split("/"):
        return ""
    return clean


def _extract_file_blocks(raw_text: str) -> Dict[str, str]:
    """Parses FILE blocks from LLM output."""
    files: Dict[str, str] = {}
    lines = raw_text.split('\n')
    current_path = None
    current_content = []
    
    for line in lines:
        stripped = line.strip()
        if stripped.startswith('FILE:'):
            if current_path and current_content:
                files[current_path.strip()] = '\n'.join(current_content)
            current_path = stripped.replace('FILE:', '').strip()
            current_content = []
        elif current_path:
            current_content.append(line)
    
    if current_path and current_content:
        files[current_path.strip()] = '\n'.join(current_content)
    
    return files


def _extract_html_document(raw_text: str, startup_name: str) -> str:
    html_doc_pattern = re.compile(r"<!doctype html.*?</html>", flags=re.IGNORECASE | re.DOTALL)
    html_pattern = re.compile(r"<html.*?</html>", flags=re.IGNORECASE | re.DOTALL)

    html_match = html_doc_pattern.search(raw_text)
    if html_match:
        return html_match.group(0).strip() + "\n"

    html_match = html_pattern.search(raw_text)
    if html_match:
        return "<!doctype html>\n" + html_match.group(0).strip() + "\n"

    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{startup_name}</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <header><h1>{startup_name}</h1></header>
  <main><p>Welcome to your startup website.</p></main>
  <footer><p>Generated by AI Startup Builder</p></footer>
  <script src="script.js"></script>
</body>
</html>
"""


def _inject_shared_assets(html: str) -> str:
    return html


def _base_page_shell(startup_name: str, page_title: str, body_content: str) -> str:
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{startup_name} | {page_title}</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <header><h1>{startup_name}</h1></header>
  <main>{body_content}</main>
  <footer><p>Generated by AI Startup Builder</p></footer>
  <script src="script.js"></script>
</body>
</html>
"""


def _default_about_page(startup_name: str, description: str) -> str:
    body = f"<h2>About {startup_name}</h2><p>{description}</p>"
    return _base_page_shell(startup_name, "About", body)


def _default_pricing_page(startup_name: str) -> str:
    body = "<h2>Pricing</h2><p>Contact us for pricing details.</p>"
    return _base_page_shell(startup_name, "Pricing", body)


def _default_contact_page(startup_name: str) -> str:
    body = "<h2>Contact</h2><p>Email: hello@example.com</p>"
    return _base_page_shell(startup_name, "Contact", body)


def _default_stylesheet() -> str:
    return """body { font-family: sans-serif; margin: 0; padding: 20px; }
h1, h2 { color: #333; }
footer { margin-top: 20px; color: #666; }
"""


def _default_script() -> str:
    return "console.log('Hello from AI Startup Builder');"


def _default_readme(startup_name: str) -> str:
    return f"# {startup_name}\n\nGenerated by AI Startup Builder."


def _fallback_file_set(raw_text: str, structured_idea: dict) -> Dict[str, str]:
    startup_name = structured_idea.get("startup_name", "Startup")
    description = str(structured_idea.get("description", "")).strip() or "A startup website."
    files = {}
    files["index.html"] = _extract_html_document(raw_text, startup_name=startup_name)
    files["about.html"] = _default_about_page(startup_name, description)
    files["pricing.html"] = _default_pricing_page(startup_name)
    files["contact.html"] = _default_contact_page(startup_name)
    files["styles.css"] = _default_stylesheet()
    files["script.js"] = _default_script()
    files["README.md"] = _default_readme(startup_name)
    return files


def _ensure_required_files(files: Dict[str, str], structured_idea: dict) -> Dict[str, str]:
    startup_name = structured_idea.get("startup_name", "Startup")
    description = str(structured_idea.get("description", "")).strip() or "A startup website."
    if "index.html" not in files:
        files["index.html"] = _extract_html_document("", startup_name=startup_name)
    if "about.html" not in files:
        files["about.html"] = _default_about_page(startup_name, description)
    if "pricing.html" not in files:
        files["pricing.html"] = _default_pricing_page(startup_name)
    if "contact.html" not in files:
        files["contact.html"] = _default_contact_page(startup_name)
    if "styles.css" not in files:
        files["styles.css"] = _default_stylesheet()
    if "script.js" not in files:
        files["script.js"] = _default_script()
    if "README.md" not in files:
        files["README.md"] = _default_readme(startup_name)
    return files


def _build_website_files(website_raw_output: str, structured_idea: dict) -> Dict[str, str]:
    parsed_files = _extract_file_blocks(website_raw_output)
    if parsed_files:
        parsed_files = _ensure_required_files(parsed_files, structured_idea)
        print(f"[INFO] Parsed {len(parsed_files)} generated files from model output.")
        return parsed_files
    fallback_files = _fallback_file_set(website_raw_output, structured_idea)
    print("[WARN] Model output was not in FILE block format. Using fallback multi-file scaffold.")
    return fallback_files


def run_startup_workflow(
    startup_idea: str,
    user_github_token: str = None,
    user_vercel_token: str = None,
    user_vercel_team_id: str = None,
):
    """Main workflow for generating idea analysis, market research, and website."""
    print("\n[INFO] Starting startup workflow...\n")
    structured_idea = preprocess_idea(startup_idea)
    print("[INFO] Running idea analysis...")
    analysis_result = safe_step(idea_analyzer_agent, idea_analysis_task, {"startup_idea": structured_idea})
    print("[INFO] Running market research...")
    research_result = safe_step(market_research_agent, market_research_task, {"startup_idea": structured_idea})
    print("[INFO] Generating website...")
    website_raw_output = ""
    try:
        website_result = safe_step(
            website_generator_agent,
            website_generation_task,
            {"startup_idea": structured_idea, "analysis": str(analysis_result), "research": str(research_result)},
        )
        website_raw_output = _extract_raw_text(website_result)
    except Exception as e:
        print(f"[WARN] Website generation step failed. Falling back to styled templates. Details: {e}")

    website_files = _build_website_files(website_raw_output, structured_idea=structured_idea)
    missing_files = [name for name in REQUIRED_SITE_FILES if name not in website_files]
    if missing_files:
        print(f"[WARN] Missing required files after normalization: {missing_files}")

    repo_name = re.sub(r"[^a-zA-Z0-9]+", "-", structured_idea["startup_name"].lower()).strip("-")
    repo_url = None
    repo_id = None
    vercel_project_name = repo_name

    try:
        repo_url, repo_id, vercel_project_name = create_github_repo(
            repo_name=repo_name,
            files=website_files,
            user_token=user_github_token,
        )
        print("\n[INFO] GitHub repo created:", repo_url)
    except Exception as e:
        print("\n[ERROR] GitHub repo creation failed:", e)

    live_url = None
    if repo_id:
        try:
            live_url = deploy_to_vercel(
                project_name=vercel_project_name,
                repo_id=repo_id,
                user_token=user_vercel_token,
                vercel_team_id=user_vercel_team_id,
            )
            print("\n[INFO] Live website URL:", live_url)
        except Exception as e:
            print("\n[ERROR] Vercel deployment failed:", e)

    return {
        "analysis_result": str(analysis_result),
        "research_result": str(research_result),
        "repo_url": repo_url,
        "live_url": live_url,
        "generated_files": sorted(list(website_files.keys())),
        "action_plan": _recommended_action_plan(structured_idea),
        "startup_name": structured_idea.get("startup_name"),
    }
